obj-$(CONFIG_INTELLI_PLUG) += intelli_plug.o
obj-$(CONFIG_BRICKED_HOTPLUG) += bricked_hotplug.o
obj-$(CONFIG_ASMP) += autosmp.o
obj-$(CONFIG_MSM_SLEEPER) += msm-sleeper.o
obj-$(CONFIG_MAKO_HOTPLUG) += mako_hotplug.o

